# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import object_detection_pb2 as object__detection__pb2


class DetectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.detect = channel.stream_stream(
        '/object_detection.Detector/detect',
        request_serializer=object__detection__pb2.Image.SerializeToString,
        response_deserializer=object__detection__pb2.Image.FromString,
        )


class DetectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def detect(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'detect': grpc.stream_stream_rpc_method_handler(
          servicer.detect,
          request_deserializer=object__detection__pb2.Image.FromString,
          response_serializer=object__detection__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'object_detection.Detector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
