# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object_detection.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='object_detection.proto',
  package='object_detection',
  syntax='proto3',
  serialized_pb=_b('\n\x16object_detection.proto\x12\x10object_detection\"\x1a\n\x05Image\x12\x11\n\tjpeg_data\x18\x01 \x01(\x0c\x32L\n\x08\x44\x65tector\x12@\n\x06\x64\x65tect\x12\x17.object_detection.Image\x1a\x17.object_detection.Image\"\x00(\x01\x30\x01\x62\x06proto3')
)




_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='object_detection.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jpeg_data', full_name='object_detection.Image.jpeg_data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'object_detection_pb2'
  # @@protoc_insertion_point(class_scope:object_detection.Image)
  ))
_sym_db.RegisterMessage(Image)



_DETECTOR = _descriptor.ServiceDescriptor(
  name='Detector',
  full_name='object_detection.Detector',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=72,
  serialized_end=148,
  methods=[
  _descriptor.MethodDescriptor(
    name='detect',
    full_name='object_detection.Detector.detect',
    index=0,
    containing_service=None,
    input_type=_IMAGE,
    output_type=_IMAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTOR)

DESCRIPTOR.services_by_name['Detector'] = _DETECTOR

# @@protoc_insertion_point(module_scope)
